[project]
name = "llm_tools_mcp_client"
version = "0.2.0"
description = "Exploring MCP tools for llm"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "llm", 
    "mcp"
]

[project.entry-points.llm]
llm_tools_mcp_client = "llm_tools_mcp_client"