[project]
name = "demo"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "llm"
]

[project.entry-points.llm]
demo = "main"